//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAccessLib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Reflection;

    public partial class tbl_product
    {
        public int productid { get; set; }

        public string categoryid { get; set; }
      
       [Required]
       [DataType("System.String")]
       [RegularExpression("[aA-zZ]*",ErrorMessage ="invalid product name,please enter only characters")]
        public string productname { get; set; }
        [Required]
        [DataType("System.Int32")]
        public Nullable<int> price { get; set; }
        [Required]
        [DataType("System.String")]
        public string description { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
